# Conexion JDBC hacia la base de datos MySQL "clinicaveterinaria".
spring.datasource.url=jdbc:mysql://localhost:3306/clinicaveterinaria
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto de Hibernate para MySQL.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Muestra en consola las sentencias SQL generadas (util para depuracion).
spring.jpa.show-sql=true

# Actualiza automaticamente el esquema de la base de datos segun las entidades.
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
